[terminal]
vt = 1

[default_session]
command = "/usr/bin/tuigreet --time --remember --user-menu --cmd 'sh -c \"XDG_CONFIG_HOME=/dev/null sway -c /etc/sway/config\"'"

user = "greeter"

[session]
initial_session = false
default_session = true
