# /etc/bashrc

[[ -z "$PS1" ]] && return

if [ -z "$BASHRCSOURCED" ]; then
    BASHRCSOURCED="Y"

    if [ -z "$PROMPT_COMMAND" ]; then
        declare -a PROMPT_COMMAND
        case "$TERM" in
            xterm*)
                if [ -e /etc/sysconfig/bash-prompt-xterm ]; then
                    PROMPT_COMMAND=/etc/sysconfig/bash-prompt-xterm
                else
                    PROMPT_COMMAND='printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
                fi
                ;;
            screen*)
                if [ -e /etc/sysconfig/bash-prompt-screen ]; then
                    PROMPT_COMMAND=/etc/sysconfig/bash-prompt-screen
                else
                    PROMPT_COMMAND='printf "\033k%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
                fi
                ;;
            *)
                [ -e /etc/sysconfig/bash-prompt-default ] && PROMPT_COMMAND=/etc/sysconfig/bash-prompt-default
                ;;
        esac
    fi

    shopt -s histappend
    shopt -s checkwinsize

    [ "$PS1" = "\\s-\\v\\\$ " ] && PS1="[\u@\h \W]\\$ "

    [ "$(umask)" -eq 0 ] && umask 022
    SHELL=/bin/bash

    if ! shopt -q login_shell; then
        for i in /etc/profile.d/*.sh; do
            if [ -r "$i" ]; then
                source "$i"
            fi
        done
        unset i
    fi

    if [ -f $BASHRC ]; then
        source $BASHRC
    fi
fi
